// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnLogin;

  @NonNull
  public final EditText editTextEmail;

  @NonNull
  public final EditText editTextPassword;

  @NonNull
  public final LinearLayout emailLayout;

  @NonNull
  public final LinearLayout fillCard;

  @NonNull
  public final LinearLayout layoutTitle;

  @NonNull
  public final LinearLayout passwordLayout;

  @NonNull
  public final ProgressBar regProgressBar;

  @NonNull
  public final TextView textViewRegister;

  private ActivityLoginBinding(@NonNull ScrollView rootView, @NonNull Button btnLogin,
      @NonNull EditText editTextEmail, @NonNull EditText editTextPassword,
      @NonNull LinearLayout emailLayout, @NonNull LinearLayout fillCard,
      @NonNull LinearLayout layoutTitle, @NonNull LinearLayout passwordLayout,
      @NonNull ProgressBar regProgressBar, @NonNull TextView textViewRegister) {
    this.rootView = rootView;
    this.btnLogin = btnLogin;
    this.editTextEmail = editTextEmail;
    this.editTextPassword = editTextPassword;
    this.emailLayout = emailLayout;
    this.fillCard = fillCard;
    this.layoutTitle = layoutTitle;
    this.passwordLayout = passwordLayout;
    this.regProgressBar = regProgressBar;
    this.textViewRegister = textViewRegister;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn_login;
      Button btnLogin = rootView.findViewById(id);
      if (btnLogin == null) {
        break missingId;
      }

      id = R.id.edit_text_email;
      EditText editTextEmail = rootView.findViewById(id);
      if (editTextEmail == null) {
        break missingId;
      }

      id = R.id.edit_text_password;
      EditText editTextPassword = rootView.findViewById(id);
      if (editTextPassword == null) {
        break missingId;
      }

      id = R.id.emailLayout;
      LinearLayout emailLayout = rootView.findViewById(id);
      if (emailLayout == null) {
        break missingId;
      }

      id = R.id.fillCard;
      LinearLayout fillCard = rootView.findViewById(id);
      if (fillCard == null) {
        break missingId;
      }

      id = R.id.layoutTitle;
      LinearLayout layoutTitle = rootView.findViewById(id);
      if (layoutTitle == null) {
        break missingId;
      }

      id = R.id.passwordLayout;
      LinearLayout passwordLayout = rootView.findViewById(id);
      if (passwordLayout == null) {
        break missingId;
      }

      id = R.id.regProgressBar;
      ProgressBar regProgressBar = rootView.findViewById(id);
      if (regProgressBar == null) {
        break missingId;
      }

      id = R.id.text_view_register;
      TextView textViewRegister = rootView.findViewById(id);
      if (textViewRegister == null) {
        break missingId;
      }

      return new ActivityLoginBinding((ScrollView) rootView, btnLogin, editTextEmail,
          editTextPassword, emailLayout, fillCard, layoutTitle, passwordLayout, regProgressBar,
          textViewRegister);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
