// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityReminderListBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView emptyView;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final FloatingActionButton reminderListAddFab;

  @NonNull
  public final FloatingActionButton reminderListBackFab;

  @NonNull
  public final TextView reminderListTitle;

  private ActivityReminderListBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView emptyView, @NonNull RecyclerView recyclerView,
      @NonNull FloatingActionButton reminderListAddFab,
      @NonNull FloatingActionButton reminderListBackFab, @NonNull TextView reminderListTitle) {
    this.rootView = rootView;
    this.emptyView = emptyView;
    this.recyclerView = recyclerView;
    this.reminderListAddFab = reminderListAddFab;
    this.reminderListBackFab = reminderListBackFab;
    this.reminderListTitle = reminderListTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityReminderListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityReminderListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_reminder_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityReminderListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.empty_view;
      TextView emptyView = rootView.findViewById(id);
      if (emptyView == null) {
        break missingId;
      }

      id = R.id.recycler_view;
      RecyclerView recyclerView = rootView.findViewById(id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.reminder_list_add_fab;
      FloatingActionButton reminderListAddFab = rootView.findViewById(id);
      if (reminderListAddFab == null) {
        break missingId;
      }

      id = R.id.reminder_list_back_fab;
      FloatingActionButton reminderListBackFab = rootView.findViewById(id);
      if (reminderListBackFab == null) {
        break missingId;
      }

      id = R.id.reminder_list_title;
      TextView reminderListTitle = rootView.findViewById(id);
      if (reminderListTitle == null) {
        break missingId;
      }

      return new ActivityReminderListBinding((ConstraintLayout) rootView, emptyView, recyclerView,
          reminderListAddFab, reminderListBackFab, reminderListTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
