// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.DatePicker;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.TimePicker;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityReminderDetailBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final DatePicker reminderDetailDatePicker;

  @NonNull
  public final TextView reminderDetailStatusText;

  @NonNull
  public final TimePicker reminderDetailTimePicker;

  private ActivityReminderDetailBinding(@NonNull ScrollView rootView,
      @NonNull DatePicker reminderDetailDatePicker, @NonNull TextView reminderDetailStatusText,
      @NonNull TimePicker reminderDetailTimePicker) {
    this.rootView = rootView;
    this.reminderDetailDatePicker = reminderDetailDatePicker;
    this.reminderDetailStatusText = reminderDetailStatusText;
    this.reminderDetailTimePicker = reminderDetailTimePicker;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityReminderDetailBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityReminderDetailBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_reminder_detail, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityReminderDetailBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.reminder_detail_date_picker;
      DatePicker reminderDetailDatePicker = rootView.findViewById(id);
      if (reminderDetailDatePicker == null) {
        break missingId;
      }

      id = R.id.reminder_detail_status_text;
      TextView reminderDetailStatusText = rootView.findViewById(id);
      if (reminderDetailStatusText == null) {
        break missingId;
      }

      id = R.id.reminder_detail_time_picker;
      TimePicker reminderDetailTimePicker = rootView.findViewById(id);
      if (reminderDetailTimePicker == null) {
        break missingId;
      }

      return new ActivityReminderDetailBinding((ScrollView) rootView, reminderDetailDatePicker,
          reminderDetailStatusText, reminderDetailTimePicker);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
