// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegistrationBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnRegister;

  @NonNull
  public final LinearLayout confirmPasswordLayout;

  @NonNull
  public final EditText editTextConfirmPassword;

  @NonNull
  public final EditText editTextEmail;

  @NonNull
  public final EditText editTextFullname;

  @NonNull
  public final EditText editTextPassword;

  @NonNull
  public final LinearLayout emailLayout;

  @NonNull
  public final LinearLayout fillCard;

  @NonNull
  public final LinearLayout layoutTitle;

  @NonNull
  public final LinearLayout passwordLayout;

  @NonNull
  public final ProgressBar regProgressBar;

  @NonNull
  public final ImageView regUserPhoto;

  @NonNull
  public final TextView textViewLogin;

  private ActivityRegistrationBinding(@NonNull ScrollView rootView, @NonNull Button btnRegister,
      @NonNull LinearLayout confirmPasswordLayout, @NonNull EditText editTextConfirmPassword,
      @NonNull EditText editTextEmail, @NonNull EditText editTextFullname,
      @NonNull EditText editTextPassword, @NonNull LinearLayout emailLayout,
      @NonNull LinearLayout fillCard, @NonNull LinearLayout layoutTitle,
      @NonNull LinearLayout passwordLayout, @NonNull ProgressBar regProgressBar,
      @NonNull ImageView regUserPhoto, @NonNull TextView textViewLogin) {
    this.rootView = rootView;
    this.btnRegister = btnRegister;
    this.confirmPasswordLayout = confirmPasswordLayout;
    this.editTextConfirmPassword = editTextConfirmPassword;
    this.editTextEmail = editTextEmail;
    this.editTextFullname = editTextFullname;
    this.editTextPassword = editTextPassword;
    this.emailLayout = emailLayout;
    this.fillCard = fillCard;
    this.layoutTitle = layoutTitle;
    this.passwordLayout = passwordLayout;
    this.regProgressBar = regProgressBar;
    this.regUserPhoto = regUserPhoto;
    this.textViewLogin = textViewLogin;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegistrationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegistrationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_registration, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegistrationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn_register;
      Button btnRegister = rootView.findViewById(id);
      if (btnRegister == null) {
        break missingId;
      }

      id = R.id.confirmPasswordLayout;
      LinearLayout confirmPasswordLayout = rootView.findViewById(id);
      if (confirmPasswordLayout == null) {
        break missingId;
      }

      id = R.id.edit_text_confirm_password;
      EditText editTextConfirmPassword = rootView.findViewById(id);
      if (editTextConfirmPassword == null) {
        break missingId;
      }

      id = R.id.edit_text_email;
      EditText editTextEmail = rootView.findViewById(id);
      if (editTextEmail == null) {
        break missingId;
      }

      id = R.id.edit_text_fullname;
      EditText editTextFullname = rootView.findViewById(id);
      if (editTextFullname == null) {
        break missingId;
      }

      id = R.id.edit_text_password;
      EditText editTextPassword = rootView.findViewById(id);
      if (editTextPassword == null) {
        break missingId;
      }

      id = R.id.emailLayout;
      LinearLayout emailLayout = rootView.findViewById(id);
      if (emailLayout == null) {
        break missingId;
      }

      id = R.id.fillCard;
      LinearLayout fillCard = rootView.findViewById(id);
      if (fillCard == null) {
        break missingId;
      }

      id = R.id.layoutTitle;
      LinearLayout layoutTitle = rootView.findViewById(id);
      if (layoutTitle == null) {
        break missingId;
      }

      id = R.id.passwordLayout;
      LinearLayout passwordLayout = rootView.findViewById(id);
      if (passwordLayout == null) {
        break missingId;
      }

      id = R.id.regProgressBar;
      ProgressBar regProgressBar = rootView.findViewById(id);
      if (regProgressBar == null) {
        break missingId;
      }

      id = R.id.regUserPhoto;
      ImageView regUserPhoto = rootView.findViewById(id);
      if (regUserPhoto == null) {
        break missingId;
      }

      id = R.id.text_view_login;
      TextView textViewLogin = rootView.findViewById(id);
      if (textViewLogin == null) {
        break missingId;
      }

      return new ActivityRegistrationBinding((ScrollView) rootView, btnRegister,
          confirmPasswordLayout, editTextConfirmPassword, editTextEmail, editTextFullname,
          editTextPassword, emailLayout, fillCard, layoutTitle, passwordLayout, regProgressBar,
          regUserPhoto, textViewLogin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
