// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CalendarView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCustomReminderBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CalendarView calendarView;

  @NonNull
  public final TextView eventTV;

  @NonNull
  public final TextView eventTV2;

  private ActivityCustomReminderBinding(@NonNull ConstraintLayout rootView,
      @NonNull CalendarView calendarView, @NonNull TextView eventTV, @NonNull TextView eventTV2) {
    this.rootView = rootView;
    this.calendarView = calendarView;
    this.eventTV = eventTV;
    this.eventTV2 = eventTV2;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCustomReminderBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCustomReminderBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_custom_reminder, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCustomReminderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.calendar_view;
      CalendarView calendarView = rootView.findViewById(id);
      if (calendarView == null) {
        break missingId;
      }

      id = R.id.eventTV;
      TextView eventTV = rootView.findViewById(id);
      if (eventTV == null) {
        break missingId;
      }

      id = R.id.eventTV2;
      TextView eventTV2 = rootView.findViewById(id);
      if (eventTV2 == null) {
        break missingId;
      }

      return new ActivityCustomReminderBinding((ConstraintLayout) rootView, calendarView, eventTV,
          eventTV2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
