// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ContentProfilesBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout paEmptyStateLinearLayout;

  @NonNull
  public final TextView paEmptyStateTextView;

  @NonNull
  public final TextView paEmptyStateTitleTextView;

  @NonNull
  public final RecyclerView profilesRecyclerView;

  @NonNull
  public final CardView setReminder;

  private ContentProfilesBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout paEmptyStateLinearLayout, @NonNull TextView paEmptyStateTextView,
      @NonNull TextView paEmptyStateTitleTextView, @NonNull RecyclerView profilesRecyclerView,
      @NonNull CardView setReminder) {
    this.rootView = rootView;
    this.paEmptyStateLinearLayout = paEmptyStateLinearLayout;
    this.paEmptyStateTextView = paEmptyStateTextView;
    this.paEmptyStateTitleTextView = paEmptyStateTitleTextView;
    this.profilesRecyclerView = profilesRecyclerView;
    this.setReminder = setReminder;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ContentProfilesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ContentProfilesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.content_profiles, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ContentProfilesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.pa_empty_state_linear_layout;
      LinearLayout paEmptyStateLinearLayout = rootView.findViewById(id);
      if (paEmptyStateLinearLayout == null) {
        break missingId;
      }

      id = R.id.pa_empty_state_text_view;
      TextView paEmptyStateTextView = rootView.findViewById(id);
      if (paEmptyStateTextView == null) {
        break missingId;
      }

      id = R.id.pa_empty_state_title_text_view;
      TextView paEmptyStateTitleTextView = rootView.findViewById(id);
      if (paEmptyStateTitleTextView == null) {
        break missingId;
      }

      id = R.id.profiles_recycler_view;
      RecyclerView profilesRecyclerView = rootView.findViewById(id);
      if (profilesRecyclerView == null) {
        break missingId;
      }

      id = R.id.setReminder;
      CardView setReminder = rootView.findViewById(id);
      if (setReminder == null) {
        break missingId;
      }

      return new ContentProfilesBinding((LinearLayout) rootView, paEmptyStateLinearLayout,
          paEmptyStateTextView, paEmptyStateTitleTextView, profilesRecyclerView, setReminder);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
