// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ProfileFsdBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageButton buttonClose;

  @NonNull
  public final NestedScrollView nestedScrollView;

  @NonNull
  public final LinearLayout newProfileBirthdayLayout;

  @NonNull
  public final TextView npTitleTvw;

  @NonNull
  public final TextView npblDateLabelTvw;

  @NonNull
  public final TextView npblDateValueTvw;

  @NonNull
  public final ImageView npblIcon;

  @NonNull
  public final Spinner npdGenderSpinner;

  @NonNull
  public final Button npdSaveButton;

  @NonNull
  public final TextInputEditText pbreedTiet;

  @NonNull
  public final TextInputLayout pbreedTil;

  @NonNull
  public final TextInputEditText pnameTiet;

  @NonNull
  public final TextInputLayout pnameTil;

  @NonNull
  public final TextInputEditText pweightTiet;

  @NonNull
  public final TextInputLayout pweightTil;

  private ProfileFsdBinding(@NonNull LinearLayout rootView, @NonNull ImageButton buttonClose,
      @NonNull NestedScrollView nestedScrollView, @NonNull LinearLayout newProfileBirthdayLayout,
      @NonNull TextView npTitleTvw, @NonNull TextView npblDateLabelTvw,
      @NonNull TextView npblDateValueTvw, @NonNull ImageView npblIcon,
      @NonNull Spinner npdGenderSpinner, @NonNull Button npdSaveButton,
      @NonNull TextInputEditText pbreedTiet, @NonNull TextInputLayout pbreedTil,
      @NonNull TextInputEditText pnameTiet, @NonNull TextInputLayout pnameTil,
      @NonNull TextInputEditText pweightTiet, @NonNull TextInputLayout pweightTil) {
    this.rootView = rootView;
    this.buttonClose = buttonClose;
    this.nestedScrollView = nestedScrollView;
    this.newProfileBirthdayLayout = newProfileBirthdayLayout;
    this.npTitleTvw = npTitleTvw;
    this.npblDateLabelTvw = npblDateLabelTvw;
    this.npblDateValueTvw = npblDateValueTvw;
    this.npblIcon = npblIcon;
    this.npdGenderSpinner = npdGenderSpinner;
    this.npdSaveButton = npdSaveButton;
    this.pbreedTiet = pbreedTiet;
    this.pbreedTil = pbreedTil;
    this.pnameTiet = pnameTiet;
    this.pnameTil = pnameTil;
    this.pweightTiet = pweightTiet;
    this.pweightTil = pweightTil;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ProfileFsdBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ProfileFsdBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.profile_fsd, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ProfileFsdBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button_close;
      ImageButton buttonClose = rootView.findViewById(id);
      if (buttonClose == null) {
        break missingId;
      }

      id = R.id.nested_scroll_view;
      NestedScrollView nestedScrollView = rootView.findViewById(id);
      if (nestedScrollView == null) {
        break missingId;
      }

      id = R.id.new_profile_birthday_layout;
      LinearLayout newProfileBirthdayLayout = rootView.findViewById(id);
      if (newProfileBirthdayLayout == null) {
        break missingId;
      }

      id = R.id.np_title_tvw;
      TextView npTitleTvw = rootView.findViewById(id);
      if (npTitleTvw == null) {
        break missingId;
      }

      id = R.id.npbl_date_label_tvw;
      TextView npblDateLabelTvw = rootView.findViewById(id);
      if (npblDateLabelTvw == null) {
        break missingId;
      }

      id = R.id.npbl_date_value_tvw;
      TextView npblDateValueTvw = rootView.findViewById(id);
      if (npblDateValueTvw == null) {
        break missingId;
      }

      id = R.id.npbl_icon;
      ImageView npblIcon = rootView.findViewById(id);
      if (npblIcon == null) {
        break missingId;
      }

      id = R.id.npd_gender_spinner;
      Spinner npdGenderSpinner = rootView.findViewById(id);
      if (npdGenderSpinner == null) {
        break missingId;
      }

      id = R.id.npd_save_button;
      Button npdSaveButton = rootView.findViewById(id);
      if (npdSaveButton == null) {
        break missingId;
      }

      id = R.id.pbreed_tiet;
      TextInputEditText pbreedTiet = rootView.findViewById(id);
      if (pbreedTiet == null) {
        break missingId;
      }

      id = R.id.pbreed_til;
      TextInputLayout pbreedTil = rootView.findViewById(id);
      if (pbreedTil == null) {
        break missingId;
      }

      id = R.id.pname_tiet;
      TextInputEditText pnameTiet = rootView.findViewById(id);
      if (pnameTiet == null) {
        break missingId;
      }

      id = R.id.pname_til;
      TextInputLayout pnameTil = rootView.findViewById(id);
      if (pnameTil == null) {
        break missingId;
      }

      id = R.id.pweight_tiet;
      TextInputEditText pweightTiet = rootView.findViewById(id);
      if (pweightTiet == null) {
        break missingId;
      }

      id = R.id.pweight_til;
      TextInputLayout pweightTil = rootView.findViewById(id);
      if (pweightTil == null) {
        break missingId;
      }

      return new ProfileFsdBinding((LinearLayout) rootView, buttonClose, nestedScrollView,
          newProfileBirthdayLayout, npTitleTvw, npblDateLabelTvw, npblDateValueTvw, npblIcon,
          npdGenderSpinner, npdSaveButton, pbreedTiet, pbreedTil, pnameTiet, pnameTil, pweightTiet,
          pweightTil);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
