// Generated by view binder compiler. Do not edit!
package com.example.petreminder.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import com.example.petreminder.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RowRemindersLvBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView customRDlt;

  @NonNull
  public final LinearLayout customreminderLL;

  @NonNull
  public final TextView reminderTimeTv;

  @NonNull
  public final TextView reminderTitleTv;

  private RowRemindersLvBinding(@NonNull LinearLayout rootView, @NonNull ImageView customRDlt,
      @NonNull LinearLayout customreminderLL, @NonNull TextView reminderTimeTv,
      @NonNull TextView reminderTitleTv) {
    this.rootView = rootView;
    this.customRDlt = customRDlt;
    this.customreminderLL = customreminderLL;
    this.reminderTimeTv = reminderTimeTv;
    this.reminderTitleTv = reminderTitleTv;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RowRemindersLvBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RowRemindersLvBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.row_reminders_lv, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RowRemindersLvBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.customR_dlt;
      ImageView customRDlt = rootView.findViewById(id);
      if (customRDlt == null) {
        break missingId;
      }

      id = R.id.customreminder_LL;
      LinearLayout customreminderLL = rootView.findViewById(id);
      if (customreminderLL == null) {
        break missingId;
      }

      id = R.id.reminderTime_tv;
      TextView reminderTimeTv = rootView.findViewById(id);
      if (reminderTimeTv == null) {
        break missingId;
      }

      id = R.id.reminderTitle_tv;
      TextView reminderTitleTv = rootView.findViewById(id);
      if (reminderTitleTv == null) {
        break missingId;
      }

      return new RowRemindersLvBinding((LinearLayout) rootView, customRDlt, customreminderLL,
          reminderTimeTv, reminderTitleTv);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
